---
- name: Percona XtraDB Galera Cluster Installation
  gather_facts: false
  hosts: all
  tasks:
     - name: Transfering Percona XtraDB install script
       copy: src=xtradb_install_galera/xtradb_install.sh dest=/tmp mode=0777

     - name: Transfering Percona XtraDB Configuration script
       copy: src=xtradb_install_galera/xtradb_install_config_galera.sh dest=/tmp mode=0777

     - name: Executing Percona XtraDB Installation script
       command: "sh /tmp/xtradb_install.sh {{ mysql_version }} {{ gtid }} {{ primary_server }} {{ galera_cluster_name }} {{ galera_cluster_address }}"
       register: cmd_install
     - debug: msg="{{ cmd_install.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_install.stderr_lines|replace('\\t',' ') }}"

     - name: Executing Percona XtraDB Configuration script
       command: sh /tmp/xtradb_install_config_galera.sh
       register: cmd_config
     - debug: msg="{{ cmd_config.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_config.stderr_lines|replace('\\t',' ') }}"

     - name: Ansible delete - Percona XtraDB install script
       file:
         path: /tmp/xtradb_install.sh
         state: absent

     - name: Ansible delete - Percona XtraDB config script
       file:
         path: /tmp/xtradb_install_config_galera.sh
         state: absent
